name: "ci"

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.14, 1.15, 1.16 ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -timeout=30s -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
